# Lab member expectations {#expectations}

All lab members are expected to adhere to our lab philosophy (Chapter \@ref(philosophy)), communication practices (Chapter \@ref(communication)), and research practices (Chapter \@ref(research)), as outlined elsewhere in this manual.


## UBC requirements

Given that our lab members have diverse departmental affiliations and are enrolled in and hired through various programs, with various funding arrangements, it is the responsibility of the individual lab member to ensure they are keeping on top of paperwork related to their own payroll, HR, travel, reimbursements, etc. We can use this lab manual and lab Slack to share information and resources with one another, and please let Dr. Noonan know if you have questions or need support.

Graduate students are responsible for their degree progress. This means you need to stay on top of program and university deadlines and requirements. For students enrolled in a graduate program in Biology, you are expected to read and be familiar with the [Graduate Student Handbook](https://biology.ok.ubc.ca/wp-content/uploads/sites/135/2026/06/Handbook-for-BIOL-Graduate-Students-2025-2026_updatedApr2026.pdf). Before registering for courses each term, you should discuss your plans with Dr. Noonan (ideally in our weekly meetings).


## Research expectations

The level of independence of lab members in research development will vary according to position, with increasing independence from undergraduate to MSc to PhD to postdocs, as well as the course of an individual's time in the lab. 

For all graduate students and postdocs, it is expected that research is your top priority during your time in the Quantitative Ecology Lab. In addition to following our lab research practices (Chapter \@ref(research)), you should plan to publish your work in peer-reviewed journals and present it at scientific conferences. Communication of your approach and findings is an essential step in the scientific process.

### Publication

Graduate students should plan to submit a minimum of half of their chapters to peer-reviewed journals prior to sign-off on their thesis. For PhD students, aim to submit one chapter to a peer-reviewed publication within the first ~2 years in the program, and a second within the first 3.5. For MSc students, aim to have one chapter submission ready by the end of the program.

Dr. Noonan and other lab members will support you in navigating the peer-review process, including journal selection, responses to reviewers, and payment of publication costs.

When you leave the lab, make a plan with Dr. Noonan for the timeline and process of submission of any additional first-authored papers from your time in the lab. If your plans change and you can no longer commit to the publication process on the timeline that we discussed, other members of the Quantitative Ecology Lab will be given the opportunity to follow through on the work (with credit given to your contributions). Dr. Noonan will talk to you to make a plan well before we reach this point.


### Conferences

Graduate students and postdocs in the Quantitative Ecology Lab are expected to share their research at local, national, and international meetings. We will share information with each other on upcoming conferences, and provide feedback on drafts of posters and presentations in lab meeting.

To ensure that we are on the same page when sharing in-progress work with the public and with the scientific community, and maintain a high level of academic rigour, you must clear any abstracts and slideshows with Dr. Noonan and other co-authors. If you submit an abstract without first consulting Dr. Noonan, you will be asked to withdraw it.

Discuss your conference interests with Dr. Noonan, and prepare a budget and justification (what will you gain by participating, what will you be presenting?). It is our goal that everyone should be able to participate in at least one local or regional conference each year (e.g. BCTWS) and one national or international conference at least once during their degree.


### Authorship policy

In our collaborative work, the person who makes the most significant intellectual contributions (in terms of conceiving the original idea, method development, experiment design, analysis) and leads the research and writing of the manuscript will be the first author.

Shared first authorship may be an option in some circumstances: for example, when projects are truly co-developed and done equally, or when leadership of a project is handed off from one lab member to another upon leaving the group. However, graduate students should plan to be the sole first author on any papers that arise from thesis chapters.

Co-authorship on a paper can be earned through substantial intellectual contribution (e.g., development of ideas, interpretation of results) or contribution to data collection, analysis, and/or writing. Contribution of data alone does not usually merit authorship, but data contributors should be given the opportunity to be co-authors by providing additional contributions. Similarly, using someone's code that was developed for a prior project does not in itself warrant co-authorship. However, if that person provides additional intellectual input such as adapting the code, interpreting results, contributing to writing authorship should be considered. All coauthors should be involved in the writing process by giving feedback on drafts.

If you are leading a project that is facilitated by undergraduate researchers and/or field technicians, you are encouraged to provide these individuals with the opportunity to contribute intellectually to the project and earn co-authorship.

It is likely that Dr. Noonan will be the last (senior) author on most publications led by lab members for research that is primarily conducted while you are in the lab. However, like all co-authors, Dr. Noonan should earn this authorship position. Generally, you should maintain open lines of communication with Dr. Noonan about your publication plans, so that he can best support you and navigate coauthorship discussions. For papers on which you are the first author and Dr. Noonan is last author, the two of you should plan to make collective decisions about the authorship of others. 

In general, discuss authorship with your colleagues early in the collaboration process, to ensure alignment of expectations and a positive working relationship. The invitation of co-authorship should be made explicitly and in writing.

As always, feel free to ask Dr. Noonan if you have any concerns or questions about authorship, either of work that you are leading or work on which you expect to be a coauthor. There are many gray areas and unique cases.

## Funding

This section applies to graduate students in the Quantitative Ecology Lab.

### PhD students

The UBC minimum graduate PhD student stipend is $40,000 annually in years 1-4. The funds to support this stipend do not come from the department. The stipend is comprised of a combination of TA-ships, fellowships, and GRAs. The exact breakdown will vary by student. This minimum stipend will apply to all PhD students in the lab, regardless of home department. As a general rule, GRA support is not provided for PhD students in years 5+. 

Tuition over the first 4 years is covered through university graduate fellowships (conditional on satisfactory progress), and Dr. Noonan will pay tuition in year 5 if not paid by a fellowship. Any PhD students in years 6+ will be responsible for paying their own tuition. Please note that students are also expected to pay [student fees](https://okanagan.calendar.ubc.ca/fees/student-fees/student-fees-established-and-approved-ubc-board-governors).

**Fellowships, grants, and other research funding**: All PhD students are expected to seek and apply for extramural funding to support their work. This includes scholarships, fellowships, and research contracts to go towards their $40,000 stipend, but also smaller grants for travel, workshop attendance, or research costs. As a general rule, all PhD students should apply for at least one grant or fellowship every year. In most cases, obtaining a fellowship will likely increase your overall take-home pay or reduce the need to TA (see details below), and may free up lab funds to support student research, travel, and conference attendance.

**TA-ships**: PhD students are expected to TA for two terms each year, by default. If a student has fellowship support >$30,000, this expectation is reduced to at least one term. Students with fellowship(s) totaling over $40,000 may choose whether or not to TA, with all TA funding going to them. Be mindful of your timeline when taking on additional TA-ships.

**GAA/Work-Learn**: Occasionally, opportunities will arise in and outside of the lab to take on an alternative paid position, not directly related to dissertation research but in service of other administrative or research needs. These alternative jobs may be Graduate Academic Assistantships (GAAs), Work-Learn positions, or other opportunities. When these positions pay the equivalent to a TAship, they will replace the expectation to TA. The salary earned in these positions will count towards the total stipend. Be mindful of your timeline however when taking on such positions. 

**GRAs**: We will use lab funds (Graduate Research Assistantships, GRAs) to bring take-home salaries to $40,000, so long as a student is making satisfactory progress towards degree. These funds should be considered a last resort, after fellowships, TAships, and other funding opportunities have been exhausted. If you are funded from lab grants and contracts, you may need to be flexible in your research and adjust the topic to better align with the current grants/contracts that we have in the lab. 


### MSc students

The minimum stipend for MSc students in the department of biology is $22,880 annually in years 1-2. The funds to support this stipend do not come from the department. The stipend is comprised of a combination of TA-ships, fellowships, and GRAs. The exact breakdown will vary by student. This minimum stipend will apply to all MSc students in the lab, regardless of home department. GRA support is not provided for MSc students in years 3+.

For MSc students in the Faculty of Science, tuition over the first 2 years is covered through university graduate fellowships (conditional on satisfactory progress), and Dr. Noonan will pay tuition in year 3 if not paid by a fellowship. Any MSc students in years 3+ will be responsible for paying their own tuition out of their stipend (unless paid by a fellowship). Please note that students are also expected to pay [student fees](https://okanagan.calendar.ubc.ca/fees/student-fees/student-fees-established-and-approved-ubc-board-governors).

**Fellowships, grants, and other research funding**: All lab members are expected to seek and apply for extramural funding to support their work. This includes scholarships, fellowships, and research contracts to go towards their $22,880 stipend, but also smaller grants for travel, workshop attendance, or research costs. As a general rule, all graduate students should apply for at least one grant or fellowship every year. In most cases, obtaining a fellowship will likely increase your overall take-home pay or reduce the need to TA (see details below), and may free up lab funds to support student research, travel, and conference attendance.

**TA-ships**: MSc students are expected to TA for two terms each year, by default. If a student has fellowship support >$12,000, they are expected to TA for at least one term. Students with fellowship(s) totaling over $20,000 may choose whether or not to TA, with all TA funding going to them. Be mindful of your timeline when taking on additional TA-ships.

**GAA/Work-Learn**: Occasionally, opportunities will arise in and outside of the lab to take on an alternative paid position, not directly related to dissertation research but in service of other administrative or research needs. These alternative jobs may be Graduate Academic Assistantships (GAAs), Work-Learn positions, or other opportunities. When these positions pay the equivalent to a TAship, they will replace the expectation to TA. The salary earned in these positions will count towards the total stipend. Be mindful of your timeline however when taking on such positions. 

**GRAs**: We will use lab funds (Graduate Research Assistantships, GRAs) to bring take-home salaries to $22,880, so long as a student is making satisfactory progress towards degree. These funds should be considered a last resort, after fellowships, TAships, and other funding opportunities have been exhausted. If you are funded from lab grants and contracts, you may need to be flexible in your research and adjust the topic to better align with the current grants/contracts that we have in the lab. 


## Community engagement

### Service and outreach

All members of the Quantitative Ecology Lab should dedicate time to serving our communities—the lab, the departments, the university, the scientific community, and the other communities of which we are a part. Creating and giving back to community is important in building and maintaining relationships, and can also help to hone leadership and professional development skills.

This service will look different for each lab member, and ideally should align with the goals that are articulated in Individual Development plans. For example, your service may be oriented towards equity and justice work, event planning, science communication, capacity building, etc. We will support each other in our service work and ensure that this work is recognized and valued.

Everybody should recognize that service burdens fall disproportionately on members of underrepresented groups. We should consider how our individual identities may shape the way that we approach service responsibilities and adjust our approaches accordingly. 

If service work is being done at the expense of satisfactory progress towards degrees and/or research, Dr. Noonan will reach out to initiate a conversation about how to best balance responsibilities to align with your goals.

<!-- ### Responsibilities to lab -->

<!-- Within the Quantitative Ecology Lab, we will assign each individual rotating roles, so that we share responsibilities and investment in our research group. These responsibilities may include organizing lab meetings, maintaining the lab website and manual, cleaning physical lab space, etc. -->

<!-- Everybody in the Quantitative Ecology Lab should seek to provide mentorship, technical support, and assistance to other lab members, especially more senior members of the group. -->

### Attendance and participation

All graduate students and postdocs in the lab are expected to attend lab meetings, BRAES and departmental seminars, and lab member thesis defenses. We should all make a concerted effort to attend social events put on by the lab, BRAES, and departments, especially those within normal work hours. 

We are all busy, and there will always be something to do that feels more "productive" or urgent than attending a seminar or social event, but we should all recognize that these events are critical for building community. Ultimately, investment in relationships in our professional community will build a network to uplift and support our research, set the groundwork for new collaborations, and lead to new professional opportunities. Even if a talk is outside of your area of interest, use it as an opportunity to reflect on effective (and ineffective) presentation approaches. You can expect Dr. Noonan to reach out to you if your absence from seminars and lab meetings is becoming a pattern.

## Work schedule

You should set the working schedule that is the right fit for you, and it is likely that what this 'fit' is will change over the course of the time you are in the lab. There is value to interacting with others as part of your work, and we do expect you will be available during normal working hours for at least some of the time during the week. Lab members should not expect others to be available during evenings and weekends. We also recognize that there will occasionally be times where there is a need to work more to meet a deadline, but this should be the exception. An expectation of overwork is __not__ to be normalised. Good planning and time management should minimise this from happening.

### Work hours for postdocs and graduate students

For graduate students and postdocs, plan to spend 40 hours/week actively working on research, teaching, and professional development activities. Some people find that tracking hours is productive for them as it helps them keep accountable to themselves. Others do not find this method useful. Regularly assess what works best for you. 

The lab's core work hours are 10 AM – 3 PM, and lab members are expected to be physically on-site as much as possible during this window. You can expect Dr. Noonan to speak with you if there is a pattern of absence. All new lab members are expected to start with a 9–5 schedule. As experience accumulates, this schedule can be modified to suit your working style. 

### Work hours for undergraduates

Undergraduate students undertaking a directed studies or honours should plan to spend 8-10 hours/week actively working on research.

### Work hours for research assistants

All research assistants in the lab are expected to complete the work hours corresponding to their position (e.g., 10 hours/week for Work-Learn positions during winter terms, 20 hours/week for Work-Learn positions during summer terms, and 35 hours/week for summer NSERC USRA). For part-time employees, it is acceptable to make occasional adjustments, but you should communicate with your supervisor (e.g., graduate student or postdoc) about any changes to your schedule, and make sure that you are putting in the total hours for which you were hired over the course of the term. If you wish to take vacation or days off that are not your typical days off, these should be communicated well in advance to your supervisor, and you should set up out-of-office notifications.

### Sickness policy

In the event that you are feeling unwell, please rest or work from home until you are feeling well again. It is not worth the risk of transmitting a communicable illness to others in the lab. Notify Dr. Noonan if you anticipate being out of the office for more than 48 hours.


### Vacation

The lab observes all UBC statutory holidays. Lab meetings or individual meetings that fall on these days are cancelled. We do not hold lab meetings or individual meetings in the Dec 20 - Jan 2 period.

Graduate students may take 15 weekdays of vacation, as per [UBC policy](https://okanagan.calendar.ubc.ca/faculties-schools-and-colleges/college-graduate-studies/academic-regulations/graduate-student-vacation-policy). You are highly encouraged to take your vacation time, and are not expected to be engaged in research or in communication with the lab while you are on vacation. Please ensure that you set up out-of-office notifications on e-mail.

There is no formal system for tracking vacation, but you should let Dr. Noonan know when you will be out of the office for longer than 1 day. Vacation times need to be pre-approved and must be pre-arranged with Dr. Noonan at least one month in advance. As with seminar attendance, you can expect Dr. Noonan to reach out to you if unrecorded absences or extended periods away from the lab are becoming a pattern.

Medical and Parental leave will be arranged with the help of department administrators. Lab members are expected to notify Dr. Noonan as early as possible to enable appropriate project management during absences.

## Research integrity

Mistakes happen. For example, you may make a coding error that accidentally changes your findings. It is always best to bring up these mistakes as soon as you recognize them, so that we can collectively decide how to proceed. 

As a group, we should aim to reduce errors through data quality control checks, peer review of code among lab members, and frequently asking questions of each other when we are uncertain about data or methodology.

Under no circumstances should you fabricate data or manipulate research to obtain a certain result. If you are feeling any pressure to do so in order to make satisfactory progress, or have begun to go down this path and are having second thoughts, please talk to Dr. Noonan immediately. 

Should it come to light that any member of the Quantitative Ecology Lab is engaging in dishonest research practices and hiding them from the group, there may be disciplinary action through UBC. This violation of trust will likely mean the end of your time in the lab.

See UBC resources:

+ [UBC's Scholarly Integrity Policy](https://responsible.research.ubc.ca/about/scholarly-integrity-initiative/ubcs-scholarly-integrity-policy)
+ [UBC Academic Honesty & Standards](https://www.grad.ubc.ca/current-students/student-responsibilities/academic-honesty-standards)
+ [UBC Intellectual Property](https://www.grad.ubc.ca/current-students/student-responsibilities/intellectual-property)
+ [UBC avoiding Plagiarism](https://www.grad.ubc.ca/current-students/student-responsibilities/dealing-plagiarism)